server:
  port: 8081
spring:
  application:
    name: order
  datasource:
    password: root
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.3.14:3306/SpringCloud?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone : http://eureka1:8761/eureka/,http://eureka2:8762/eureka/

idworker:
  workerId: 2
  datacenterId: 3
env: 
  dev
