spring:
  application:
    name: user
  datasource:
    password: root
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.3.10:3306/SpringCloud?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
idworker:
  workerId: 1
  datacenterId: 1
